apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-app
  namespace: mysite
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
        - name: app
          image: "179901290133.dkr.ecr.us-west-2.amazonaws.com/mysite:IMAGE_TAG_PLACEHOLDER"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: mysite
spec:
  selector:
    name: app
  ports:
    - port: 8080
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysite-app
  namespace: mysite
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 8080

                  