name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs: 
  deploy:
    strategy: 
      matrix: 
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        image: [hello-world, alpine]  # Note: Use singular "image" for clarity.

    runs-on: ${{ matrix.os }}

    steps: 
      - name: Set up Docker
        run: |
          echo "Setting up Docker on ${{ matrix.os }}"

      - name: Echo Docker Details
        run: docker info

      - name: Run Image on ${{ matrix.os }}
        run: |
          echo "Running Docker image: ${{ matrix.image }}"
          docker run ${{ matrix.image }}
